### ISSUE TITLE
Separate Expressions from the Data/Manipulation part of the package.

### ISSUE THREAD

**Issue by agorzawski** [tensorics/tensorics-core#12]
It is more like a reminder that at some moment it may be useful to separate this part from the others as it can exists on its own...

**Comment by kaifox** [comment]
Part of this was done by Andrea recently. Still a final cleanup is for sure necessary....

**Comment by kaifox** [comment]
In the end, this approach turned out to be quite challenging and probably the wrong approach: Who would depend on what? Tensorics on the expressions or the expressions on tensorics (both can potentially be used individually). Or do we need a third package? But these diamond problems seem to be neverending... (e.g. iterables, tensors, expressions of iterables, expressions of tensors ... )....
In the end, we decided to merge back the expression part into core, but try to keep the package structure internally as clean as possible (no circular package deps).

The only part which still seems to make sense to drag apart for the moment is the one with the quantities, because these introduce an additional dependancy (jscience) - for the moment.

**Comment by kaifox** [comment]
Will not be done for the moment
